TWITCH_CLIENT_ID = 'twitch_client_id'
TWITCH_CLIENT_SECRET = 'twitch_client_secret'

CHAT_TYPE = 'chat_type'
CHAT_TYPE_TWITCH = 'TW'
TWITCH_CHAT_SKIP = 'twitch_chat_skip'

HIGHLIGHTS_TYPE = 'highlights_type'
HIGHLIGHTS_TYPE_AVG = 'AVG'
AVG_HIGHLIGHTS_TIC = 'avg_highlights_tic'
AVG_HIGHLIGHTS_PERCENT = 'avg_highlights_percent'
AVG_HIGHLIGHTS_SKIP_CALC = 'avg_highlights_skip_calc'

DOWNLOADER_TYPE = 'downloader_type'
DOWNLOADER_TYPE_TWITCH_VOD = 'TWV'
TWITCH_VOD_DOWNLOADER_QUALITY = 'twitch_vod_downloader_quality'

SPEECH_DETECTOR_TYPE = 'speech_detector_type'
SPEECH_DETECTOR_TYPE_VOSK = 'VOS'
SPEECH_DETECTOR_MAX_OF_SILENCE = 'speech_detector_max_of_silence'
SPEECH_DETECTOR_ADDITIONAL_BEGIN = 'speech_detector_additional_begin'
SPEECH_DETECTOR_ADDITIONAL_END = 'speech_detector_additional_end'
VOSK_SPEECH_DETECTOR_MODEL = 'vosk_speech_detector_model'

VIDEOEDITOR_TRANSITION_TYPE = 'videoeditor_transition_type'
TRANSITION_TYPE_CROSSFADEIN = 'CFI'

UPLOADER_TYPE = 'uploader_type'
UPLOADER_TYPE_YOUTUBE = 'YOU'
UPLOADER_TYPE_YOUTUBE_SELENIUM = 'YSE'
YOUTUBE_UPLOADER_CLIENT_SECRETS = 'youtube_uploader_client_secrets'
YOUTUBE_UPLOADER_CREDENTIALS = 'youtube_uploader_credentials'
YOUTUBE_UPLOADER_TITLE = 'youtube_uploader_title'
YOUTUBE_UPLOADER_DESCRIPTION = 'youtube_uploader_description'
YOUTUBE_UPLOADER_TAGS = 'youtube_uploader_tags'
YOUTUBE_UPLOADER_CATEGORY = 'youtube_uploader_category'
YOUTUBE_UPLOADER_DEFAULT_LANGUAGE = 'youtube_uploader_default_language'
YOUTUBE_UPLOADER_PRIVACY = 'youtube_uploader_privacy'
YOUTUBE_UPLOADER_PLAYLIST = 'youtube_uploader_playlist'

YOUTUBE_SELENIUM_UPLOADER_COOKIES_FOLDER = 'youtube_selenium_uploader_cookies_folder'
YOUTUBE_SELENIUM_UPLOADER_EXTENSIONS_FOLDER = 'youtube_selenium_uploader_extensions_folder'
YOUTUBE_SELENIUM_UPLOADER_COOKIE = 'youtube_selenium_uploader_cookie'

PIPELINE_NAME_OF_COMPILATIONS = 'pipeline_name_of_compilations'
PIPELINE_COMPILATION_LENGTH = 'pipeline_compilation_length'
PIPELINE_MAX_OF_COMPILATIONS = 'pipeline_max_of_compilations'
PIPELINE_TO_CHECK_MUSIC_LICENSE = 'pipeline_to_check_music_license'
PIPELINE_TO_CUT_SPEECH = 'pipeline_to_cut_speech'


ID = 'id'
PIPELINE_SETTINGS = 'pipeline_settings'
PROJECT = 'project'
COMPILATION = 'compilation'
COMPILATION_VIDEO = 'compilation_video'
SOURCE = 'source'

COMPILATION_SOURCE = 'source'
COMPILATION_SOURCE_LOCATION = 'source_location'
COMPILATION_STATUS = 'status'
COMPILATION_STATUS_ACTIVE = 'AC'
COMPILATION_STATUS_PAUSE = 'PA'
COMPILATION_STATUS_QUEUE = 'QU'
COMPILATION_STATUS_PROGRESS = 'PR'
COMPILATION_STATUS_READY = 'RE'
COMPILATION_LAST_PART = 'last_part'

COMPILATION_VIDEO_LOCATION = 'location'
COMPILATION_VIDEO_NAME = 'name'

SOURCE_TYPE = 'type'
SOURCE_NAME = 'name'
SOURCE_TITLE_PATTERN = 'title_pattern'
SOURCE_TYPE_TWITCH = 'TW'
SOURCE_CREDENTIALS = 'credentials'
SOURCE_AUTO_COMPILE = 'auto_compile'
SOURCE_LOCATION = 'location'
